title: Cruise-effect
author: Fanghui.Z
email: 
description: > # this means to ignore newlines until "baseurl:"
  
# social links
# twitter_username: your-twitter-handle
$ github_username:  your-github-handle


theme: just-the-docs

aux_links:
    "Project page on GitHub":
      - "https://github.com/fanghuiz/cruise-effect"
   # "Back to Homepage":
   #   - "https://github.com/fanghuiz/"

layout: default
