title: Cruise-effect
author: Fanghui.Z
email: 
description: > # this means to ignore newlines until "baseurl:"
  
# social links
# twitter_username: your-twitter-handle
$ github_username:  your-github-handle



theme: jekyll-theme-minimal
